# Schema for the configuration files of the Killam Rentcafe Integration module.
killam_rentcafe.settings:
  type: config_object
  label: 'Killam Rentcafe Integration settings'
  mapping:
    example:
      type: string
      label: 'Example'
